# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "azurerm" {
    container_name       = "tfstate"
    key                  = ".terraform_new1.tfstate"
    resource_group_name  = "Terraform-State-File"
    storage_account_name = "mytfstatefile"
    subscription_id      = "5d798471-bf04-46ec-8de0-8e42a4c1da3e"
  }
}
