# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
    terraform {
      required_providers {
        azurerm = {
          source = "hashicorp/azurerm"
          version = "3.35.0"
        }
      }
    }
    provider "azurerm" {
        features {}
        subscription_id = "5d798471-bf04-46ec-8de0-8e42a4c1da3e"
    }
